Add sleep functionality Close #1

diff --git a/loop b/loop
--- a/loop
+++ b/loop
@@ -3,6 +3,7 @@
 COMMAND=""
 EXIT_CODES=()
 TIMEOUT=""
+SLEEP=""
 
 print_help() {
 cat << HELP
@@ -10,12 +11,15 @@ cat << HELP
   The exit code '0' is implicitly included.
   Additionally, a timeout value may be supplied.
   Setting the timeout to '0' has the same effect as not supplying it.
+  The sleep option may be used to make the script wait before executing the command again.
 
-  Usage: loop <-c command> [-t timeout][-e exit codes]
+  Usage: loop <-c command> [-t timeout][-e exit codes][-s sleep duration]
 
   Examples:
     loop -c "curl https://www.google.com"             -- Call curl until it exits with 0.
     loop -c "wget https://www.google.com" -e "4 5 6"  -- Call wget until it exits with 0, 4, 5 or 6.
+    loop -c "traceroute google.com" -s 3              -- Call traceroute until it exits with 0,
+                                                         "sleeping" 3 seconds between each call.
     loop -c "ping https://www.google.com" -t 20 -e 1  -- Call ping until it exits with 0 or 1, or 20 seconds has passed.
 
   Exit codes:
@@ -32,11 +36,12 @@ main() {
 }
 
 set_options() {
-  while getopts ':c:t:e:h' opt; do
+  while getopts ':c:t:e:s:h' opt; do
     case ${opt} in
       c) COMMAND="${OPTARG}" ;;
       t) TIMEOUT="${OPTARG}" ;;
       e) EXIT_CODES=("${OPTARG}") ;;
+      s) SLEEP="${OPTARG}" ;;
       h) print_help && exit 101 ;;
       \?|*) print_help && exit 101 ;;
     esac
@@ -50,9 +55,11 @@ loop_command() {
   local exit_code=0
   local timed_out=1
   local deadline=$(($(date +%s) + TIMEOUT))
+
   until [[ ${timed_out} -eq 0 || ${finished} -eq 0 ]]; do
     ${BASH} -c "${COMMAND}"
     exit_code=$?
+    sleep "${SLEEP}"
     finished=$(exit_code_matches ${exit_code})
     timed_out=$(get_timed_out_value ${deadline})
   done
@@ -96,6 +103,7 @@ validate_options() {
   exit_on_missing_command
   set_default_timeout
   set_default_exit_code
+  set_default_sleep
   prepare_exit_codes
   validate_numeric_params
 }
@@ -119,6 +127,12 @@ set_default_exit_code() {
   fi
 }
 
+set_default_sleep() {
+  if [[ -z "${SLEEP}" ]]; then
+    SLEEP=0
+  fi
+}
+
 prepare_exit_codes() {
   EXIT_CODES+=(0)
   mapfile -t EXIT_CODES < <(printf "%s\n" "${EXIT_CODES[@]}" | sort -u)
@@ -126,14 +140,20 @@ prepare_exit_codes() {
 
 validate_numeric_params() {
   if ! is_number "${TIMEOUT}"; then
-    echo "Invalid value '${TIMEOUT}' for timeout."
+    echo "looper: Invalid value '${TIMEOUT}' for timeout."
+    echo "looper: exiting"
+    exit 101
+  fi
+
+  if ! is_number "${SLEEP}"; then
+    echo "looper: Invalid value '${SLEEP}' for sleep."
     echo "looper: exiting"
     exit 101
   fi
 
   for elem in "${EXIT_CODES[@]}"; do
     if ! is_number "${elem}"; then
-      echo "Invalid value '${elem}' for exit code."
+      echo "looper: Invalid value '${elem}' for exit code."
       echo "looper: exiting"
       exit 101
     fi
